spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://c3gavqucrhq10.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d3s4h3kcm8f1rd?sslmode=require
    username: u7ubt6fu0nmm80
    password: p25187fe4cb813704f34643bcfd8c7e4dd899b048ddd481a36a71e7fb75ed0842
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    properties:
      mail:
        debug: 'true'
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtppro.zoho.eu
    username: noreply@medbay.life
    password: "#W4p.%G#&hQA93v"
    port: '587'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
