spring:
  mvc:
    servlet:
      path: /api
  jpa:
    hibernate:
      ddl-auto: create-drop
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    properties:
      mail:
        debug: 'true'
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtppro.zoho.eu
    username: noreply@medbay.life
    port: '587'
  servlet:
    multipart:
      max-file-size: 20MB
