spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://c8fjkh5jgmh0gl.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/db0dpqnvcdshtm?sslmode=require
    username: ubgnqt5u3o5dq9
    password: p0e5697aadd4b380ffd959d7be0ab8f07a8eb7f94fa681aefea0f74047a1542ed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ian.balen6@gmail.com
    password: rzhpahsrvphcurhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.mail: DEBUG