spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://ec2-18-202-8-133.eu-west-1.compute.amazonaws.com:5432/dchravp02iqvc7?sslmode=require
    username: izeomfybqtqfat
    password: 57f3bdf387a0979cd7ff8941aba9feb48e65d0758746716e10ba8ca092a5cb73
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    properties:
      mail:
        debug: 'true'
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtppro.zoho.eu
    username: noreply@medbay.life
    password: "#W4p.%G#&hQA93v"
    port: '587'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
