spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:5434/MedBay
    username: postgres
    password: bazepodataka
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ivan7575k@gmail.com
    password: "rnje ggip hqis uwyy"
    port: '587'

