spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:5434/MedBay
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtppro.zoho.eu
    username: noreply@medbay.life
    password: "#W4p.%G#&hQA93v"
    port: '587'

